-- AlterTable
ALTER TABLE `user` ADD COLUMN `followers` INTEGER NULL DEFAULT 0,
    ADD COLUMN `hashedPassword` VARCHAR(191) NULL,
    ADD COLUMN `isActive` BOOLEAN NULL DEFAULT true,
    ADD COLUMN `registeredAt` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3);
